/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthGate: typeof import('./src/components/AuthGate.vue')['default']
    CardEditPanel: typeof import('./src/components/CardEditPanel.vue')['default']
    CardGallery: typeof import('./src/components/CardGallery.vue')['default']
    CardPreview: typeof import('./src/components/CardPreview.vue')['default']
    CardTypeEditor: typeof import('./src/components/CardTypeEditor.vue')['default']
    CardTypeHistory: typeof import('./src/components/CardTypeHistory.vue')['default']
    CsvUploader: typeof import('./src/components/CsvUploader.vue')['default']
    DataWorkbench: typeof import('./src/components/DataWorkbench.vue')['default']
    FieldMapper: typeof import('./src/components/FieldMapper.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    ProjectManager: typeof import('./src/components/ProjectManager.vue')['default']
    ProjectMaterials: typeof import('./src/components/ProjectMaterials.vue')['default']
    ProjectRules: typeof import('./src/components/ProjectRules.vue')['default']
    QuestionnaireBuilder: typeof import('./src/components/QuestionnaireBuilder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UColorModeButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UDashboardGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UProgress: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  }
}
