/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardGallery: typeof import('./src/components/CardGallery.vue')['default']
    CardPreview: typeof import('./src/components/CardPreview.vue')['default']
    CardTypeEditor: typeof import('./src/components/CardTypeEditor.vue')['default']
    CsvUploader: typeof import('./src/components/CsvUploader.vue')['default']
    FieldMapper: typeof import('./src/components/FieldMapper.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
